console.log("HELLO WORLD")
console.log("Намайг" + name + "гэдэг. Би" + age + "настай.")
console.log("Hello", 'string')
console.log(true, 'booleang')
console.log("Name", 'string')
console.log(33, 'number')
console.log("90", 'number')
console.log(90+"77", 'number')
console.log( {name:'Anu', age:15}, 'number'  )
console.log(false,  )
console.log(1655/5,  )
console.log(["javascript", "html", "css"])